version: "3.7"
services:
    web:
        image: getrector_org
        restart: unless-stopped
        build:
            context: .
            target: dev
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal"
            PHP_IDE_CONFIG: "serverName=getrector_org"
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/getrector.org:cached
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
            - demo:/var/rector-tmp
        tmpfs:
            - /var/www/getrector.org/var/cache
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "getrector_org"
        volumes:
            - ./.docker/mysql-data:/var/lib/mysql
        ports:
            - 3306:3306

volumes:
    demo:
        name: rector-demo
