# template only routes → template
research_thank_you:
    path: 'research/thank-you'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template: 'research/thank-you.twig'
