parameters:
    local_demo_dir: '%kernel.project_dir%/var/demo'
    host_demo_dir: '%env(HOST_DEMO_DIR)%'
    rector_demo_docker_image: 'rector/rector:0.6.11'

    # @todo
    demo_links:
        # https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#typedpropertyrector
        -
            label: "PHP 7.4 Typed Properties"
            uuid: "c4f35db2-fe8d-4dde-bf3c-29c580dc60a1"

        # https://github.com/rectorphp/rector/blob/master/docs/AllRectorsOverview.md#createfunctiontoanonymousfunctionrector
        -
            label: "create_function()"
            uuid: "63843c0a-d24f-4e73-a9b4-5b96c82bdd2e"

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Rector\Website\:
        resource: '../src/'
        exclude:
            - '../src/Entity/*'
            - '../src/Exception/*'
            - '../src/GetRectorKernel.php'
            - '../src/ValueObject/*'
            - '../src/Validator/Constraint/*'

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    # needs to be registered manually, because it doesn't work without priority :/
    # see https://symfony.com/doc/current/controller/argument_value_resolver.html
    Rector\Website\HttpKernel\Controller\RectorRunValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 550 }
