parameters:
    local_demo_dir: '%kernel.project_dir%/var/demo'
    host_demo_dir: '%env(HOST_DEMO_DIR)%'
    rector_demo_docker_image: 'rector/rector-secured:latest'
    demo_executable_path: '%kernel.project_dir%/bin/run-demo.sh'
    forbidden_functions:
        - 'exec'
        - 'passthru'
        - 'shell_exec'
        - 'system'
        - 'proc_open'
        - 'popen'
        - 'curl_exec'
        - 'curl_multi_exec'
        - 'parse_ini_file'
        - 'show_source'
        - 'mail'

    demo_links:
        # https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#typedpropertyrector
        -
            label: "PHP 7.4 Typed Properties"
            uuid: "c4f35db2-fe8d-4dde-bf3c-29c580dc60a1"

        # https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#createfunctiontoanonymousfunctionrector
        -
            label: "create_function()"
            uuid: "63843c0a-d24f-4e73-a9b4-5b96c82bdd2e"

        # https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#changeifelsevalueassigntoearlyreturnrector
        -
            label: "Early Return"
            uuid: "f9782921-32b6-4a0b-a9aa-779506d4ed3a"

        # https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#consecutivenullcomparereturnstonullcoalescequeuerector
        -
            label: "Null Coalescing"
            uuid: "21f4705d-c654-4b45-9ca8-2e8b68f8ec54"


services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Rector\Website\:
        resource: '../src/'
        exclude:
            - '../src/GetRectorKernel.php'

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']
