parameters:
    local_demo_dir: '%kernel.project_dir%/var/demo'
    host_demo_dir: '%env(HOST_DEMO_DIR)%'
    rector_demo_docker_image: 'rector/rector:0.6.11'

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Rector\Website\:
        resource: '../src/'
        exclude:
            - '../src/GetRectorKernel.php'
            - '../src/Entity/*'
            - '../src/ValueObject/*'
            - '../src/Exception/*'

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    # needs to be registered manually, because it doesn't work without priority :/
    # see https://symfony.com/doc/current/controller/argument_value_resolver.html
    Rector\Website\HttpKernel\Controller\UuidValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }
