parameters:
    site_url: "https://getrector.org"

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: "%kernel.project_dir%"

    Rector\Website\Blog\:
        resource: '../src/'
        exclude:
            - '../src/ValueObject/*'
            - '../src/DependencyInjection/*'

    # for rendering markdown posts
    ParsedownExtra:
        class: 'ParsedownExtra'

    Symplify\SmartFileSystem\Finder\FinderSanitizer: null
