name: Code_Checks

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    ecs:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer fix-cs

    phpstan:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer phpstan

    rector:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer rector

    unit_tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none # default is xdebug
                    extensions: mbstring # needed by phpunit

            -   run: composer install --no-progress
            -   run: vendor/bin/phpunit

    test_coverage:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: pcov
                    extensions: mbstring # needed by phpunit

            -   run: composer install --no-progress
            -   run: |
                    vendor/bin/phpunit --coverage-clover coverage.xml
                    # Coveralls.io
                    wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
                    php php-coveralls.phar --verbose
                env:
                    COVERALLS_REPO_TOKEN: 'aG2qi4W6HtQM7jhHcTYoyOjoz2RCHFbGk'
