name: Container build check

on:
    pull_request:
        branches:
            - master

jobs:
    warmup:
        name: Cache warmup
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build image
              run: |
                docker pull rector/getrector.org || true
                docker build . --cache-from rector/getrector.org -t image --target production

            - name: Warmup cache
              run: docker run -e APP_ENV=prod image bin/console cache:warmup
