name: Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: master

            - name: Log into registry
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: Build and push image
              run: |
                # Cache multi-stage builds: https://pythonspeed.com/articles/faster-multi-stage-builds/

                docker pull rector/getrector.org:base || true
                docker pull rector/getrector.org:node-build || true
                docker pull rector/getrector.org:latest || true

                docker build . --tag rector/getrector.org:base --target base \
                  --cache-from rector/getrector.org:base

                docker build . --tag rector/getrector.org:node-build --target node-build \
                  --cache-from rector/getrector.org:base \
                  --cache-from rector/getrector.org:node-build

                docker build . --tag rector/getrector.org:latest --target production \
                  --build-arg commitHash=${{ GITHUB_SHA }} \
                  --cache-from rector/getrector.org:base \
                  --cache-from rector/getrector.org:node-build \
                  --cache-from rector/getrector.org:latest

                docker push rector/getrector.org:base
                docker push rector/getrector.org:node-build
                docker push rector/getrector.org:latest

            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USERNAME }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  script: "cd /projects/getrector.org && ./run.sh"
