name: Code_Checks

on:
    - pull_request

jobs:
    ecs:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -
                name: Install
                run:
                    composer install --no-progress

            -
                name: Run
                run:
                    composer fix-cs

    phpstan:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -
                name: Install
                run:
                    composer install --no-progress

            -
                name: Run
                run:
                    composer phpstan

    rector:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -
                name: Install
                run:
                    composer install --no-progress

            -
                name: Run
                run:
                    composer rector

    unit_tests:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none # default is xdebug
                    extensions: mbstring # needed by phpunit

            -
                name: Install
                run:
                    composer install --no-progress

            -
                name: Run
                run:
                    vendor/bin/phpunit
